[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['js', 'jsx']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
# {{{
on_ft = ['jsx', 'tsx']
hook_add = '''

" dark red
hi tsxTagName guifg=#E06C75

" orange
hi tsxCloseString guifg=#F99575
hi tsxCloseTag guifg=#F99575
hi tsxCloseTagName guifg=#F99575
hi tsxAttributeBraces guifg=#F99575
hi tsxEqual guifg=#F99575

" yellow
hi tsxAttrib guifg=#F8BD7F cterm=italic
'''
# }}}

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['ts', 'tsx']

[[plugins]]
repo = 'styled-components/vim-styled-components'
on_ft = ['jsx', 'tsx']

# [[plugins]]
# repo = 'posva/vim-vue'
# on_ft = ['vue']

# [[plugins]]
# repo = 'digitaltoad/vim-pug'
# on_ft = ['vue']

# [[plugins]]
# repo = 'prettier/vim-prettier'
# build = 'npm install'
# on_ft = ['javascript', 'typescript', 'vue', 'json']
# hook_add = '''
# let g:prettier#autoformat = 0
# autocmd BufWritePre *.js,*.ts,*.vue,*.css,*.scss,*.json,*.md PrettierAsync
# '''
