[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
" colorscheme hybrid
'''

[[plugins]]
repo = 'KeitaNakamura/neodark.vim'
hook_add = '''
colorscheme neodark

" "au MyAutoCmd VimEnter * nested call SetHighlightOptions()
" "function SetHightlightOptions()
"   colorscheme neodark " example
"   highlight Normal ctermbg=NONE guibg=NONE
"   highlight NonText ctermbg=NONE guibg=NONE
"   highlight LineNr ctermbg=NONE guibg=NONE
"   highlight Folded ctermbg=NONE guibg=NONE
"   highlight EndOfBuffer ctermbg=NONE guibg=NONE
" "endfunction

augroup TransparentBG
  	autocmd!
	autocmd Colorscheme * highlight Normal ctermbg=none
	autocmd Colorscheme * highlight NonText ctermbg=none
	autocmd Colorscheme * highlight LineNr ctermbg=none
	autocmd Colorscheme * highlight Folded ctermbg=none
	autocmd Colorscheme * highlight EndOfBuffer ctermbg=none 
	autocmd Colorscheme * highlight SignColumn ctermbg=none 
augroup END
'''
