[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
  let g:jedi#use_tabs_not_buffers = 1 "補完で次の候補に進むときにtabを使えるという設定にしたつもりですができませんでした。
  let g:jedi#popup_select_first = 0 "1個目の候補が入力されるっていう設定を解除
  let g:jedi#popup_on_dot = 0 " .を入力すると補完が始まるという設定を解除
  let g:jedi#goto_command = "<leader>d"
  let g:jedi#goto_assignments_command = "<leader>g"
  let g:jedi#goto_definitions_command = ""
  let g:jedi#documentation_command = "K"
  let g:jedi#usages_command = "<leader>n"
  let g:jedi#rename_command = "<leader>R" "quick-runと競合しないように大文字Rに変更. READMEだと<leader>r
  autocmd FileType python setlocal completeopt-=preview "ポップアップを表示しない
'''

[[plugins]]
repo = 'vim-scripts/taglist.vim'
on_ft = ['c', 'cpp', 'python', 'java', 'go', 'javascript', 'ruby']
hook_add = '''
let Tlist_Ctags_Cmd = "~/.linuxbrew/Cellar/ctags"
let g:Tlist_Show_One_File = 1
let g:Tlist_Auto_Open = 1            " TagListをVim起動時に開くか (0,1)
let g:Tlist_Auto_Update = 1          " 新規ファイルを開いた時に自動的にタグリストに追加するか
let g:Tlist_Close_On_Select = 1      " タグを選択時に、画面遷移後にタグリストを閉じるか
let g:Tlist_Exit_OnlyWindow = 1      " タグリストだけが表示されているときに自動的にVimを終了するか
let g:Tlist_File_Fold_Auto_Close = 1 " ファイルが非アクティブのとき自動的にタグリストを閉じるか
'''

