[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = '''
" call lexima#add_rule({'char': '<CR>', 'at': '(\%#$', 'input_after': '<CR>)', 'except': '\C\v^(\s*)\S.*%#\n%(%(\s*|\1\s.+)\n)*\2\)'})
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
nmap <C-h> <Plug>(GitGutterNextHunk)
nmap <C-p> <Plug>(GitGutterPrevHunk)
'''

# [[plugins]]
# repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_vert_resize = 1
let g:winresizer_horiz_resize = 1
'''

[[plugins]]
repo = 'lambdalisue/gin.vim'
on_source =' lightline.vim'

[[plugins]]
repo = 'vim-test/vim-test'

# [[plugins]]
# repo = 'windwp/nvim-ts-autotag'

[[plugins]]
repo = 'ihch/mtnf.vim'
